### Site Settings ###
title               : Razvan Canuci
description         : Welcome to my personal website! ðŸ‘‹
baseurl             : ""            
repository          : razvancanuci/razvancanuci.github.io
remote_theme        : yousinix/portfolYOU
open_new_tab        : true       


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:        
  - pages/tags.html                                  
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Razvan Canuci
  image             : https://imgur.com/a/wpWpw9R
  github            : razvancanuci
  linkedin          : razvan-canuci
  medium            : razvan.canuci


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus


### Analytics ###
analytics:
  enabled: true                         
  google:
    tracking_id: G-F4E6ST0S6E


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
